server:
  error:
    include-stacktrace: never

  datasource:
    driver-class-name=org: postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}

  jpa:
    show-sql: false
    hibernate:
      dialect=org:
        hibernate:
          dialect: PostgreSQLDialect

logging:
  level:
    ROOT: INFO
    web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

