server:
  port: ${PORT:4896}

base-url: /api

spring:
  application:
    name: app

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

rollbar_token: ${ROLLBAR_TOKEN}

