server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
#    hikari:
#      auto-commit:false
#    driverClassName: org.postgresql.Driver
#    username: "sa"
#    password: "sa"
#    url: "jdbc:postgresql://localhost:5432/task_manager"
    url: "jdbc:h2:./task_manager"

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  logging:
    level:
      root: INFO
      web: DEBUG
