server:
  port: ${PORT:4896}

base-url: /api

spring:
  application:
    name: app

  profiles:
    active: ${APP_ENV:prod}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none


  mvc:
    hiddenmethod:
      filter:
        enabled: true

  rollbar_token: ${ROLLBAR_TOKEN:7bffcd5a8d6d4f86929d018889fc075d}


